<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>latest</LangVersion>
    <OutputPath>..\..\Libraries</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <AppendConfigurationToOutputPath>false</AppendConfigurationToOutputPath>
    <DebugType>embedded</DebugType>
    <RootNamespace>ModdingOverhauled</RootNamespace>
    <MSBuildWarningsAsMessages>MSB3277</MSBuildWarningsAsMessages>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>true</Optimize>
    <DefineConstants>TRACE;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup>
    <GameDir>/home/eragon/.local/share/Steam/steamapps/common/Stardeus/Stardeus_Data/Managed</GameDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="$(GameDir)/*.dll">
      <Private>false</Private>
    </Reference>
  </ItemGroup>


  <ItemGroup>
    <AdditionalFiles
            Include="..\..\Config\**\*.json"
            Link="Config\%(RecursiveDir)%(Filename)%(Extension)" />
    <AdditionalFiles
            Include="..\..\Definitions\**\*.json"
            Link="Definitions\%(RecursiveDir)%(Filename)%(Extension)" />
    <AdditionalFiles
            Include="..\..\Patches\**\*.json"
            Link="Patches\%(RecursiveDir)%(Filename)%(Extension)" />
    <AdditionalFiles
            Include="..\..\Translations\**\*.csv"
            Link="Translations\%(RecursiveDir)%(Filename)%(Extension)" />
    <Content Include="..\..\ModInfo.json">
      <Link>ModInfo.json</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IsExternalInit" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <!-- Automatic version incrementation -->

  <Target Name="IncrementModVersion" AfterTargets="Build">
    <IncrementModVersion JsonFile="$(ProjectDir)..\..\ModInfo.json" />
  </Target>
  <UsingTask TaskName="IncrementModVersion" AssemblyFile="$(MSBuildProjectDirectory)\..\Tasks\StardeusVersionController.dll" />
</Project>